# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "guppy-workspace-hack"

# Setting workspace.resolver = "2" in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the new feature resolver.
# For more about the new feature resolver, see:
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver
resolver = "2"

# Version of `workspace-hack = ...` lines in other `Cargo.toml` files to use.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config#dep-format-version for more.
dep-format-version = "2"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

exact-versions = true

[traversal-excludes]
workspace-members = [
    # Exclude the "cargo-compare" package from consideration because it is only used
    # for some test runs in CI.
    "cargo-compare",
]
